apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: node-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: node-app
